project:
  type: website
  resources:
    - "resources/"
    - "app/"

website:
  title: "ASA DataFest"
  site-url: "https://asa-datafest.netlify.app/"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: upcoming-events.qmd
        text: Upcoming Events
      - href: resources.qmd
        text: Resources
      - href: getting-started.qmd
        text: Tutorials
      - href: contact.qmd
        text: Contact

  sidebar:
    - title: "Tutorials"
      style: "docked"
      collapse-level: 2
      contents:
        - getting-started.qmd
        - EDA Jenny Final.qmd
        - Kiva_motivation_hypotest.qmd
        - Kiva_motivation_TextAnalysis.qmd
        - regression.qmd

format:
  html:
    theme: custom.scss
    toc: true

editor: visual

execute:
  freeze: auto

