{
  "hash": "d77a98399a265381730c0f2da034005f",
  "result": {
    "markdown": "---\ntitle: \"Exploratory Data Analysis\"\noutput: \n  html_document:\n  toc: true\n  toc_float: true\n---\n\n\n## Introduction and set-up\n\nIn this section of the tutorial, we guide you through the process of Exploratory Data Analysis (EDA) using the Kiva dataset and prompt introduced in the **Getting Started** section. The purpose of EDA is to perform initial investigation on the data, look for interesting trends, relationships, and anomalies through the use of descriptive statistics and data visualization. The insights generated from this stage will motivate and inspire the subsequent analysis, modelling, and statistical tests performed at the next phase in your DataFest journey.\n\n### Loading packages\n\nSince you've already been through the **Getting Started** tutorial, your R environment is all set up! With the prompt in mind, let's take a look at the data. But first, let's load some useful packages. In this tutorial, we will mainly explore and visualize the data using `tidyverse`, a collection of incredibly useful packages for doing Data Science in $\\texttt{R}$. Since countries in the dataset are recorded as country codes, the package `countrycode` will help to translate country code into country names. `colorblindr` and `viridis` are packages for colors in ggplot2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#load packages\nlibrary(tidyverse)\nlibrary(countrycode)\nlibrary(colorblindr)\nlibrary(viridis)\n```\n:::\n\n\n### Overview of the Data\n\nRecall the prompt: **Help understand what motivates people to lend money to developing-nation entrepreneurs and what factors are associated with paying these loans.** There are two parts of the prompt that we need to address, **motivation for lending** and **factors associated with repayment**.\n\nFrom the file names and data dictionary, `lender_loans.csv`, `lenders.csv`, and `loans.csv` seem to be three most relevant files. We can take a quick peek at the data before diving more deeply in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#read data\nlender_loans <- read_csv(\"data/lender_loans.csv\")\nlenders <- read_csv(\"data/lenders.csv\")\nloans <- read_csv(\"data/loans.csv\")\n\n#get the structure of the data\nstr(lender_loans)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [125,580 × 51] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ lender_id                    : chr [1:125580] \"0288537\" \"0288537\" \"0312857\" \"0589889\" ...\n $ lender_name                  : chr [1:125580] \"028\" \"028\" \"031\" \"058\" ...\n $ lender_image_id              : num [1:125580] 679954 679954 679959 680181 680181 ...\n $ whereabouts                  : chr [1:125580] NA NA NA NA ...\n $ country_code                 : chr [1:125580] NA NA NA NA ...\n $ uid                          : chr [1:125580] \"0288537\" \"0288537\" \"0312857\" \"0589889\" ...\n $ personal_url                 : chr [1:125580] NA NA NA NA ...\n $ occupation                   : chr [1:125580] NA NA NA NA ...\n $ loan_because                 : chr [1:125580] NA NA NA NA ...\n $ occupational_info            : chr [1:125580] NA NA NA NA ...\n $ loan_count                   : num [1:125580] 2 2 1 2 2 2 2 2 2 81 ...\n $ invitee_count                : num [1:125580] 0 0 0 0 0 0 0 0 0 0 ...\n $ member_since_yr              : num [1:125580] 2010 2010 2010 2010 2010 ...\n $ member_since_mo              : num [1:125580] 12 12 12 12 12 1 1 1 1 3 ...\n $ member_since_day             : num [1:125580] 28 28 28 28 28 7 7 7 7 14 ...\n $ member_since_hr              : num [1:125580] 11 11 11 16 16 15 15 15 15 23 ...\n $ member_since_min             : num [1:125580] 26 26 32 11 11 24 24 46 46 44 ...\n $ member_since_sec             : num [1:125580] 27 27 37 46 46 56 56 49 49 24 ...\n $ loan_id                      : num [1:125580] 323400 261579 261600 261684 382189 ...\n $ borrower_name                : chr [1:125580] \"Anonymous\" \"Aileen\" \"Munhjargal\" \"Antonio Desiderio\" ...\n $ borrower_image_id            : num [1:125580] 726677 679804 679894 680105 985366 ...\n $ status                       : chr [1:125580] \"in_repayment\" \"paid\" \"in_repayment\" \"paid\" ...\n $ loan_amount                  : num [1:125580] 450 200 1225 375 425 ...\n $ funded_amount                : num [1:125580] 450 200 1225 375 425 ...\n $ paid_amount                  : num [1:125580] 151.1 200 717.4 375 25.3 ...\n $ activity                     : chr [1:125580] \"Personal Housing Expenses\" \"Farming\" \"Cafe\" \"Personal Housing Expenses\" ...\n $ sector                       : chr [1:125580] \"Housing\" \"Agriculture\" \"Food\" \"Housing\" ...\n $ use                          : chr [1:125580] \"To by ceramic tiles.\" \"To purchase seeds and fertilizers\" \"To buy a refrigerator and dishes for her caf\\xe9\" \"home improvements\" ...\n $ delinquent                   : logi [1:125580] TRUE FALSE FALSE FALSE FALSE FALSE ...\n $ location.country_code        : chr [1:125580] \"NI\" \"PH\" \"MN\" \"PE\" ...\n $ location.country             : chr [1:125580] \"Nicaragua\" \"Philippines\" \"Mongolia\" \"Peru\" ...\n $ location.town                : chr [1:125580] NA \"Banga, South Cotabato\" \"Hovd, Hovd\" \"Santiago\" ...\n $ location.geo.level           : chr [1:125580] \"country\" \"town\" \"country\" \"country\" ...\n $ lat                          : num [1:125580] 13 6.42 46 -10 13.83 ...\n $ lon                          : num [1:125580] -85 124.8 105 -76 -88.9 ...\n $ partner_id                   : num [1:125580] 74 125 116 139 199 116 93 93 117 61 ...\n $ borrower_count               : num [1:125580] 1 1 1 1 1 1 8 8 5 1 ...\n $ currency_exchange_loss_amount: num [1:125580] NA NA NA NA NA NA NA NA NA NA ...\n $ video.youtube_id             : chr [1:125580] NA NA NA NA ...\n $ posted_yr                    : num [1:125580] 2011 2010 2010 2010 2012 ...\n $ posted_mo                    : num [1:125580] 8 12 12 12 1 1 8 8 1 12 ...\n $ posted_day                   : num [1:125580] 7 28 28 28 23 5 29 29 7 1 ...\n $ posted_hr                    : num [1:125580] 20 10 11 15 3 5 18 20 14 8 ...\n $ posted_min                   : num [1:125580] 30 0 30 20 20 40 20 0 20 3 ...\n $ posted_sec                   : num [1:125580] 14 8 6 9 4 6 4 27 15 8 ...\n $ planned_expiration_yr        : num [1:125580] NA NA NA NA 2012 ...\n $ planned_expiration_mo        : num [1:125580] NA NA NA NA 2 NA NA NA NA NA ...\n $ planned_expiration_day       : num [1:125580] NA NA NA NA 22 NA NA NA NA NA ...\n $ planned_expiration_hr        : num [1:125580] NA NA NA NA 3 NA NA NA NA NA ...\n $ planned_expiration_min       : num [1:125580] NA NA NA NA 20 NA NA NA NA NA ...\n $ planned_expiration_sec       : num [1:125580] NA NA NA NA 4 NA NA NA NA NA ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   lender_id = col_character(),\n  ..   lender_name = col_character(),\n  ..   lender_image_id = col_double(),\n  ..   whereabouts = col_character(),\n  ..   country_code = col_character(),\n  ..   uid = col_character(),\n  ..   personal_url = col_character(),\n  ..   occupation = col_character(),\n  ..   loan_because = col_character(),\n  ..   occupational_info = col_character(),\n  ..   loan_count = col_double(),\n  ..   invitee_count = col_double(),\n  ..   member_since_yr = col_double(),\n  ..   member_since_mo = col_double(),\n  ..   member_since_day = col_double(),\n  ..   member_since_hr = col_double(),\n  ..   member_since_min = col_double(),\n  ..   member_since_sec = col_double(),\n  ..   loan_id = col_double(),\n  ..   borrower_name = col_character(),\n  ..   borrower_image_id = col_double(),\n  ..   status = col_character(),\n  ..   loan_amount = col_double(),\n  ..   funded_amount = col_double(),\n  ..   paid_amount = col_double(),\n  ..   activity = col_character(),\n  ..   sector = col_character(),\n  ..   use = col_character(),\n  ..   delinquent = col_logical(),\n  ..   location.country_code = col_character(),\n  ..   location.country = col_character(),\n  ..   location.town = col_character(),\n  ..   location.geo.level = col_character(),\n  ..   lat = col_double(),\n  ..   lon = col_double(),\n  ..   partner_id = col_double(),\n  ..   borrower_count = col_double(),\n  ..   currency_exchange_loss_amount = col_double(),\n  ..   video.youtube_id = col_character(),\n  ..   posted_yr = col_double(),\n  ..   posted_mo = col_double(),\n  ..   posted_day = col_double(),\n  ..   posted_hr = col_double(),\n  ..   posted_min = col_double(),\n  ..   posted_sec = col_double(),\n  ..   planned_expiration_yr = col_double(),\n  ..   planned_expiration_mo = col_double(),\n  ..   planned_expiration_day = col_double(),\n  ..   planned_expiration_hr = col_double(),\n  ..   planned_expiration_min = col_double(),\n  ..   planned_expiration_sec = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nstr(lenders)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [15,000 × 18] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ lender_id        : chr [1:15000] \"matt\" \"hope\" \"jeevan\" \"stephen6473\" ...\n $ lender_name      : chr [1:15000] \"Matt\" \"Hope\" \"Jeevan\" \"Stephen\" ...\n $ lender_image_id  : num [1:15000] 12829 9494 74234 726677 125417 ...\n $ whereabouts      : chr [1:15000] \"San Francisco CA\" \"Bellevue WA\" \"San Francisco CA\" \"Rankin IL\" ...\n $ country_code     : chr [1:15000] \"US\" \"US\" \"US\" \"US\" ...\n $ uid              : chr [1:15000] \"matt\" \"hope\" \"jeevan\" \"stephen6473\" ...\n $ personal_url     : chr [1:15000] \"twitter.com/mattflannery\" NA NA NA ...\n $ occupation       : chr [1:15000] \"Entrepreneur\" NA \"consultant of some kind\" NA ...\n $ loan_because     : chr [1:15000] \"I love the stories.\" NA \"it is the right thing to do.\" NA ...\n $ occupational_info: chr [1:15000] \"I co-founded a startup nonprofit (this one!) and I work with an amazing group of people dreaming up ways to all\"| __truncated__ NA \"I work with small computers and make them do nice stuff for people, if all goes well.\" NA ...\n $ loan_count       : num [1:15000] 137 2 11 13 17 8 151 32 74 0 ...\n $ invitee_count    : num [1:15000] 32 0 0 0 0 1 3 0 0 0 ...\n $ member_since_yr  : num [1:15000] 2006 2006 2006 2006 2006 ...\n $ member_since_mo  : num [1:15000] 1 1 1 1 1 1 1 1 1 1 ...\n $ member_since_day : num [1:15000] 1 1 1 1 1 1 1 1 1 1 ...\n $ member_since_hr  : num [1:15000] 9 9 9 9 9 9 9 9 9 9 ...\n $ member_since_min : num [1:15000] 1 1 1 1 1 1 1 1 1 1 ...\n $ member_since_sec : num [1:15000] 1 1 1 1 1 1 1 1 1 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   lender_id = col_character(),\n  ..   lender_name = col_character(),\n  ..   lender_image_id = col_double(),\n  ..   whereabouts = col_character(),\n  ..   country_code = col_character(),\n  ..   uid = col_character(),\n  ..   personal_url = col_character(),\n  ..   occupation = col_character(),\n  ..   loan_because = col_character(),\n  ..   occupational_info = col_character(),\n  ..   loan_count = col_double(),\n  ..   invitee_count = col_double(),\n  ..   member_since_yr = col_double(),\n  ..   member_since_mo = col_double(),\n  ..   member_since_day = col_double(),\n  ..   member_since_hr = col_double(),\n  ..   member_since_min = col_double(),\n  ..   member_since_sec = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n\n```{.r .cell-code}\nstr(loans)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nspec_tbl_df [97,183 × 75] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ loan_id                               : num [1:97183] 89 102 122 124 147 193 194 199 211 212 ...\n $ borrower_name                         : chr [1:97183] \"Rose\" \"Simon\" \"Joseph\" \"Richard\" ...\n $ borrower_image_id                     : num [1:97183] 246 264 287 294 726677 ...\n $ status                                : chr [1:97183] \"paid\" \"paid\" \"paid\" \"paid\" ...\n $ funded_amount                         : num [1:97183] 500 500 500 500 0 375 225 375 475 375 ...\n $ paid_amount                           : num [1:97183] 500 500 500 500 NA 375 225 375 475 375 ...\n $ activity                              : chr [1:97183] \"Food Production/Sales\" \"Pharmacy\" \"Animal Sales\" \"Crafts\" ...\n $ sector                                : chr [1:97183] \"Food\" \"Health\" \"Agriculture\" \"Arts\" ...\n $ use                                   : chr [1:97183] \"Buying and reselling of produce\" \"Buying of medicine for rural drug shop\" \"Buy goats\" \"To buy more stock\" ...\n $ location.country_code                 : chr [1:97183] \"UG\" \"UG\" \"UG\" \"TZ\" ...\n $ location.country                      : chr [1:97183] \"Uganda\" \"Uganda\" \"Uganda\" \"Tanzania\" ...\n $ location.town                         : chr [1:97183] \"Tororo\" \"Soroti\" \"Soroti\" \"Dodoma\" ...\n $ location.geo.level                    : chr [1:97183] \"town\" \"town\" \"town\" \"town\" ...\n $ lat                                   : num [1:97183] 0.75 1.58 1.58 -6.18 43 ...\n $ lon                                   : num [1:97183] 34.1 33.6 33.6 35.8 25 ...\n $ partner_id                            : num [1:97183] 1 1 1 1 3 5 5 5 5 5 ...\n $ posted_yr                             : num [1:97183] 2005 2005 2005 2005 2006 ...\n $ posted_mo                             : num [1:97183] 4 10 11 11 2 3 3 3 3 3 ...\n $ posted_day                            : num [1:97183] 15 15 15 15 15 15 15 15 15 15 ...\n $ posted_hr                             : num [1:97183] 17 17 18 18 18 18 18 18 18 18 ...\n $ posted_min                            : num [1:97183] 0 0 0 0 0 0 0 0 0 0 ...\n $ posted_sec                            : num [1:97183] 0 0 0 0 0 0 0 0 0 0 ...\n $ loan_amount                           : num [1:97183] 500 500 500 500 1000 375 225 375 475 375 ...\n $ terms.disbursal_amount                : num [1:97183] 500 500 500 500 1000 375 225 375 475 375 ...\n $ terms.loan_amount                     : num [1:97183] 500 500 500 500 1000 375 225 375 475 375 ...\n $ terms.loss_liability.nonpayment       : chr [1:97183] \"lender\" \"lender\" \"lender\" \"lender\" ...\n $ terms.loss_liability.currency_exchange: chr [1:97183] \"none\" \"none\" \"none\" \"none\" ...\n $ terms.disbursal_currency              : chr [1:97183] NA NA NA NA ...\n $ terms.disbursal_yr                    : num [1:97183] 2005 2005 2005 2005 2006 ...\n $ terms.disbursal_mo                    : num [1:97183] 4 4 4 4 3 4 4 4 4 4 ...\n $ terms.disbursal_day                   : num [1:97183] 14 14 14 14 15 14 14 14 14 14 ...\n $ terms.disbursal_hr                    : num [1:97183] 5 5 5 5 5 5 5 5 5 5 ...\n $ terms.disbursal_min                   : num [1:97183] 27 27 27 27 0 27 27 27 27 27 ...\n $ terms.disbursal_sec                   : num [1:97183] 55 55 55 55 0 55 55 55 55 55 ...\n $ funded_yr                             : num [1:97183] 2005 2005 2005 2005 NA ...\n $ funded_mo                             : num [1:97183] 3 3 3 3 NA 3 3 3 3 3 ...\n $ funded_day                            : num [1:97183] 31 31 31 31 NA 31 31 31 31 31 ...\n $ funded_hr                             : num [1:97183] 6 6 6 6 NA 6 6 6 6 6 ...\n $ funded_min                            : num [1:97183] 27 27 27 27 NA 27 27 27 27 27 ...\n $ funded_sec                            : num [1:97183] 55 55 55 55 NA 55 55 55 55 55 ...\n $ paid_yr                               : num [1:97183] 2005 2006 2006 2007 NA ...\n $ paid_mo                               : num [1:97183] 12 10 11 1 NA 3 12 3 11 4 ...\n $ paid_day                              : num [1:97183] 13 24 23 14 NA 1 26 1 28 25 ...\n $ paid_hr                               : num [1:97183] 12 5 15 21 NA 16 3 16 17 16 ...\n $ paid_min                              : num [1:97183] 9 7 11 26 NA 37 49 37 39 18 ...\n $ paid_sec                              : num [1:97183] 18 52 7 56 NA 9 58 5 33 53 ...\n $ journal_totals.entries                : num [1:97183] 14 9 11 2 2 2 2 2 2 2 ...\n $ delinquent                            : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ video.youtube_id                      : chr [1:97183] NA NA NA NA ...\n $ currency_exchange_loss_amount         : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_yr                 : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_mo                 : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_day                : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_hr                 : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_min                : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ planned_expiration_sec                : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ description                           : chr [1:97183] \"<i>\\nThe following description was written by Moses Onyango, a volunteer with Village Enterprise Fund and partner representativ \"Simon O. is married and has 7 children.\\n<br><br>\\nSimon O. started a drug shop after selling 3 goats he had reared at home for \"Joseph is married with five children. He started goat rearing after he attended the training that was organized by Village Ente \"<i>This description was written by Richard Mazengo, a staff member for Village Enterprise Fund in Tanzania.  He is also a partn ...\n $ description.en                        : logi [1:97183] TRUE TRUE TRUE TRUE TRUE TRUE ...\n $ description.fr                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.es                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.vi                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.ru                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.pt                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.id                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ description.ar                        : logi [1:97183] FALSE FALSE FALSE FALSE FALSE FALSE ...\n $ borrower_names                        : chr [1:97183] \"Rose\" \"Simon\" \"Joseph\" \"Richard\" ...\n $ borrower_count                        : num [1:97183] 1 1 1 1 1 1 1 1 1 1 ...\n $ borrower_m_count                      : num [1:97183] 0 1 1 1 1 0 0 0 0 0 ...\n $ borrower_f_count                      : num [1:97183] 1 0 0 0 0 1 1 1 1 1 ...\n $ borrower_pic_count                    : num [1:97183] 1 1 1 1 1 1 1 1 1 1 ...\n $ scheduled_payments.count              : num [1:97183] 0 0 0 0 0 0 0 0 0 0 ...\n $ scheduled_payments.avg_dollar_amount  : num [1:97183] NA NA NA NA NA NA NA NA NA NA ...\n $ payments.count                        : num [1:97183] 9 6 8 4 10 9 7 9 7 11 ...\n $ payments.dollar_total                 : num [1:97183] 55.6 83.3 62.5 125 100 ...\n $ payments.local_total                  : num [1:97183] 55.6 83.3 62.5 125 100 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   loan_id = col_double(),\n  ..   borrower_name = col_character(),\n  ..   borrower_image_id = col_double(),\n  ..   status = col_character(),\n  ..   funded_amount = col_double(),\n  ..   paid_amount = col_double(),\n  ..   activity = col_character(),\n  ..   sector = col_character(),\n  ..   use = col_character(),\n  ..   location.country_code = col_character(),\n  ..   location.country = col_character(),\n  ..   location.town = col_character(),\n  ..   location.geo.level = col_character(),\n  ..   lat = col_double(),\n  ..   lon = col_double(),\n  ..   partner_id = col_double(),\n  ..   posted_yr = col_double(),\n  ..   posted_mo = col_double(),\n  ..   posted_day = col_double(),\n  ..   posted_hr = col_double(),\n  ..   posted_min = col_double(),\n  ..   posted_sec = col_double(),\n  ..   loan_amount = col_double(),\n  ..   terms.disbursal_amount = col_double(),\n  ..   terms.loan_amount = col_double(),\n  ..   terms.loss_liability.nonpayment = col_character(),\n  ..   terms.loss_liability.currency_exchange = col_character(),\n  ..   terms.disbursal_currency = col_character(),\n  ..   terms.disbursal_yr = col_double(),\n  ..   terms.disbursal_mo = col_double(),\n  ..   terms.disbursal_day = col_double(),\n  ..   terms.disbursal_hr = col_double(),\n  ..   terms.disbursal_min = col_double(),\n  ..   terms.disbursal_sec = col_double(),\n  ..   funded_yr = col_double(),\n  ..   funded_mo = col_double(),\n  ..   funded_day = col_double(),\n  ..   funded_hr = col_double(),\n  ..   funded_min = col_double(),\n  ..   funded_sec = col_double(),\n  ..   paid_yr = col_double(),\n  ..   paid_mo = col_double(),\n  ..   paid_day = col_double(),\n  ..   paid_hr = col_double(),\n  ..   paid_min = col_double(),\n  ..   paid_sec = col_double(),\n  ..   journal_totals.entries = col_double(),\n  ..   delinquent = col_logical(),\n  ..   video.youtube_id = col_character(),\n  ..   currency_exchange_loss_amount = col_double(),\n  ..   planned_expiration_yr = col_double(),\n  ..   planned_expiration_mo = col_double(),\n  ..   planned_expiration_day = col_double(),\n  ..   planned_expiration_hr = col_double(),\n  ..   planned_expiration_min = col_double(),\n  ..   planned_expiration_sec = col_double(),\n  ..   description = col_character(),\n  ..   description.en = col_logical(),\n  ..   description.fr = col_logical(),\n  ..   description.es = col_logical(),\n  ..   description.vi = col_logical(),\n  ..   description.ru = col_logical(),\n  ..   description.pt = col_logical(),\n  ..   description.id = col_logical(),\n  ..   description.ar = col_logical(),\n  ..   borrower_names = col_character(),\n  ..   borrower_count = col_double(),\n  ..   borrower_m_count = col_double(),\n  ..   borrower_f_count = col_double(),\n  ..   borrower_pic_count = col_double(),\n  ..   scheduled_payments.count = col_double(),\n  ..   scheduled_payments.avg_dollar_amount = col_double(),\n  ..   payments.count = col_double(),\n  ..   payments.dollar_total = col_double(),\n  ..   payments.local_total = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n:::\n:::\n\n\nUsing the `str` function, we can see that in `lender_loans`, we have 125,580 observations of 51 variables; in `lenders`, we have 15,000 observations of 18 variables; and in `loans`, we have 97,183 observations of 75 variables. We can also see the variable names, from which we can narrow down our scope to the variables that are relevant to the prompt for further exploration and analysis.\n\nTo investigate lenders' motivations, we focus on the files `lender_loans` and `lenders`. Potentially useful lender-level variables include `country_code` (lenders' country), `occupation` (lenders' occupation), as well as the time that each lender has been a member of Kiva (variables start with `member_since`). The variable `loan_because` will be particularly revealing since it contains direct quotes from lenders related to their reasons for lending. However, because it contains complex free text data, it requires different analytical approaches that will be covered later in the **Text Analysis** section.\n\nVariables that may contribute to loan repayment include `loan_amount`, `sector`, and `location.code` (borrowers' country). A larger `loan_amount` may be associated with higher risk enterprise. Certain `sectors` may be more profitable than others. The macroeconomic environment of a location may be associated with the success of borrowers.\n\nThere are also some variables that may be relevant to both parts of the prompt, such as the time when the loan request was posted and the loan amount. For instance, in 2008, the world economy underwent a global financial crisis. We might expect that this would have simultaneously increased the demand and decreased the supply of loans. Additionally, we might expect increased defaults as borrowers struggle to repay existing loans. To explore these hypotheses and more, we begin our analysis.\n\n## EDA\n\nWe begin by visualizing the distribution of potentially important variables.\n\n### -- LOOKING AT THE BIG PICTURE --\n\n#### Loan Amount\n\nLet's start simple. To get a general sense of the loan amount, we can plot a histogram with the `loan_amount` on the x-axis and the percentage on the y-axis. Histograms is one of the most basic and direct visualization graphs for continuous variables. We can also color the bars to see the proportion of loans in different statuses to add another layer of information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Format variable names for legend \nlender_loans$status <- gsub(\"in_repayment\", \"in repayment\", lender_loans$status)\nlender_loans$status <- sub(\"(.)\", \"\\\\U\\\\1\",lender_loans$status,perl=TRUE)\n\n#Plot the Loan amount distribution\nggplot(lender_loans, aes(x = loan_amount, fill = status, width = 0.1)) +\n  geom_bar(aes(y=(..count..)/sum(..count..)), stat = \"bin\", color = \"black\") +\n  xlab(\"Loan amount\") +\n  ylab(\"Percentage\") +\n  scale_fill_OkabeIto()+\n  scale_fill_discrete(name = \"Status\")+\n  ggtitle(\"Distribution of loan amount and the status of each loan amount\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/loan_amount dist-1.png){width=768}\n:::\n:::\n\n\nFrom the graph above we can see that the loan amount has a unimodal, skewed right distribution. The interquartile range of loan amount is \\$600 USD to \\$1975 USD, although loans as high as \\$10,000 USD are observed in the dataset. From this, we see that most loans are relatively small in relation to income in the United States. Examining the distribution of loan status, we see that more than half of the loans have been repaid or are still in repayment, while relatively few loans are in default.\n\nA summary table may be more direct to visualize the proportion of each status:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Format variable names for legend \nloans$status <- gsub(\"in_repayment\", \"in repayment\", loans$status)\nloans$status <- sub(\"(.)\", \"\\\\U\\\\1\", loans$status, perl=TRUE)\n\n#Arrange statuses of loans by frequency\nstatus <- loans %>%\n  drop_na(status) %>% # drop missing values by health variable\n  group_by(status) %>% # specify categorical variable \n  rename(\"Status\" = \"status\") %>% \n  summarize(Frequency = n()) %>% # return counts / frequencies\n  arrange(desc(Frequency)) %>% \n  mutate(Percent = paste0(round(Frequency / nrow(loans) * 100, 2), \"%\"))\n\n#Output the table\ntable1 <- tibble(status)\nknitr::kable(table1, \"pipe\")\n```\n\n::: {.cell-output-display}\n|Status       | Frequency|Percent |\n|:------------|---------:|:-------|\n|Paid         |     67144|69.09%  |\n|In repayment |     26971|27.75%  |\n|Defaulted    |      1563|1.61%   |\n|Refunded     |       973|1%      |\n|Fundraising  |       291|0.3%    |\n|Expired      |       226|0.23%   |\n|Inactive     |        13|0.01%   |\n|Funded       |         2|0%      |\n:::\n:::\n\n\nIn the table, we can tell that approximately 69% of loans are paid, and about 28% are in repayment. Therefore, in general, 98% of loans are being paid or already paid, while fewer than 2% are in default.\n\n#### Loan amount and number of loans across year\n\nNext, we investigate trends over time involving the value and number of loans. From the barchart below, we can see that both the total loan amount and the number of loans issued each year continued to grow until 2012. The highest loan amount borrowed was in the year 2011 at USD 40.2 million. Similarly, the highest of number of loans were taken in the year 2011 as well, at 30,738 loans.\n\nIt appears that Kiva activity plummeted in 2012. However, investigating further we see that the 2012 data only includes values up to April: for all years under `posted_yr`, the corresponding `posted_month` goes from 1 to 12, except for 2012, where `posted_month` stops at 4. Further, we verify by locating Kiva's publicly available financial reporting documents, that Kiva's fiscal year ends on December 31th each year. Hence, the apparent 2012 anomaly is just an artifact of data collection which must be considered in subsequent analysis.\n\n\n::: {.cell header='false'}\n\n```{.r .cell-code}\n# Summarise loan amount by year\nyear_loan_amount <- loans %>%\n  group_by(posted_yr) %>%\n  summarise(Total_amount = sum(loan_amount) / 1000) %>%\n  mutate(year = factor(posted_yr, posted_yr))\n\n# Summarise loan count by year\nyear_loan_count <- loans %>%\n  group_by(posted_yr) %>%\n  summarise(counts = length(unique(loan_id))) %>%\n  mutate(year = factor(posted_yr, posted_yr))\n\n# Clean data\nyear_loan_amount <- na.omit(year_loan_amount)\nyear_loan_count <- na.omit(year_loan_count)\n\npar(mfrow = c(1, 1))\n\n# Plot loan amount by year\nggplot(year_loan_amount) +\n  aes(x = year, y = Total_amount, group = 1, label = Total_amount) +\n  geom_line() +\n  geom_text(size = 3, nudge_y = 1000) +\n  theme(legend.position = \"none\") +\n  xlab(\"Year\") +\n  ylab(\"Total loan amount in USD ('000)\") +\n  scale_fill_OkabeIto()+\n  ggtitle(\"Distribution of Loan amount over the years\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/across year-1.png){width=80%}\n:::\n\n```{.r .cell-code}\n# Plot loan count by year\nggplot(year_loan_count) +\n  aes(x = year, y = counts, group = 1, label = counts) +\n  geom_line() +\n  geom_text(size = 3, nudge_y = 1000) +\n  theme(legend.position = \"none\") +\n  xlab(\"Year\") +\n  ylab(\"Total number of loans\") +\n  scale_fill_OkabeIto()+\n  ggtitle(\"Distribution of number of loans over the years\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/across year-2.png){width=80%}\n:::\n:::\n\n\n#### Loan amount and number of loans across country\n\nNext, we consider geographical trends in the Kiva data. Since there are 65 many countries participating in both lending and borrowing through Kiva, it will be difficult to visualize trends for all countries. To simplify, we select the top 10 countries with the most transactions in the 2011 data (the most recent complete data year). To further simplify our visualization, we omit the incomplete 2012 data.\n\n*Geographical Distribution of Borrowers*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identifying top 10 borrower countries\ntop_10_borrower_table <- lender_loans %>% \n  group_by(location.country) %>% \n  summarize(total_amount_borrower = sum(loan_amount)) %>% \n  arrange(desc(total_amount_borrower))\ntop_10_bor<- unique(top_10_borrower_table$location.country)[1:10]\n\n# Loan Amount by year\nloan_amount_country <- aggregate(lender_loans$loan_amount, by = list(year = lender_loans$posted_yr, country = lender_loans$location.country), FUN = sum, na.rm = TRUE) %>% \n  rename(\"loan_amount\" = \"x\") %>% \n  mutate(loan_amount = loan_amount/1000) %>% \n  filter(country %in% top_10_bor, year < 2012)\n\n# Bar Chart loan amount vs year by country\nggplot(loan_amount_country) +\n  geom_line(aes(x=year, y=loan_amount, fill = country, color = country)) +\n  xlab(\"Year\") +\n  ylab(\"Total loan count (thousand dollars)\") +\n  scale_fill_viridis(\n  discrete = TRUE,\n  option = \"D\")+\n  ggtitle(\"Top 10 borrower countries by loan amount\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/loan distribution across borrower country-1.png){width=672}\n:::\n:::\n\n\nFrom the graph above, we see that in half of the top ten borrower countries (Mexico, Paraguay, Tajikistan, Tanzania, and United States), the loan amount increased from 2005 to 2011, while Uganda, Cambodia, and Peru reached their peak in 2010 and experienced a decrease in loan amount in 2011. Bolivia had the highest loan amount at \\$4,500,000 ever in 2009, but the loan amount has declined subsequently.\n\n*Geographical Distribution of Lenders*\n\n\n::: {.cell header='false'}\n\n```{.r .cell-code}\n# Identifying top 10 lender countries\ntop_10_lender_table <- lender_loans %>% \n  group_by(country_code) %>% \n  summarize(total_amount_lender = sum(loan_amount)) %>%\n  arrange(desc(total_amount_lender)) %>% \n  na.omit(country_code)\ntop_10_lender<- unique(top_10_lender_table$country_code)[1:10]\n\n# Summarize the loan amount based on the lenders' country by year\ncountry <- aggregate(lender_loans$loan_amount, by = list(year = lender_loans$posted_yr, country = lender_loans$country_code), FUN = sum, na.rm = TRUE)\n\n# Convert coutry codes to country names\ncountry_decoded <- country %>%\n  rename(\"country_name\" = \"country\", \"loan_amount\" = \"x\") %>%\n  filter(country_name %in% top_10_lender, year < 2012) %>%\n  mutate(country_name = countrycode(country_name, \"iso2c\", \"country.name\"))\n\n# Plot the total loan amount by lender countries graph\nggplot(data = country_decoded, aes(x = year, y = log(loan_amount), color = country_name)) +\n  geom_line() +\n  xlab(\"Year\") +\n  ylab(\"Loan amount (log)\") +\n  guides(color = guide_legend(title = \"Country\")) +\n  scale_fill_viridis(\n  discrete = TRUE,\n  option = \"D\")+\n  ggtitle(\"Top 10 lender countries by total loan amount from 2005 to 2012\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/Lenders Trend-1.png){width=672}\n:::\n:::\n\n\nHere, we visualize loans originating in the top ten lender countries over time. In this case, we can improve our visualization by taking the logarithm of the loan amount. This is because the US has a significantly higher total loan amount compared to other countries, due to the fact that Kiva is based in the US. As a result, plotting data in the raw scale makes it difficult to distinguish between all other lenders. We note that all of the top ten lender countries have increased their loan amount over time. While the majority of top lenders are high income countries, with the exception of the Philippines. We might expect that lender motivation may differ in high and low countries, and so this is something to bear in mind and we proceed with the lender-focused analysis.\n\n### -- Part 1: Lender Motivation --\n\nTo understand lender motivation, we begin with some background easily located via Kiva's webiste: Kiva provides a platform where borrowers post their credit needs, and lenders choose how much and to whom they lend. Hence, the decision to lend to a specific borrower is purely up to lenders and may reveal their preferences and motivations. Further, we might look at the characteristics of funded and non-funded borrowers in hopes of identifying patterns.\n\n#### Regional lending trends\n\nWe explore the heterogeneity in lending practices by identifying the top recipient countries ( as determined by the total dollar value of loans received) for each of the top lenders. In the table below, Borrower 1 refers to the top recipient country, Borrower 2 refers to the second largest recipient, and so on. Overall, while Peru and Uganda are popular recipient countries, a variety of countries from Asia, Africa, and South America show up as well. The table reveals that on aggregate, lenders do not prefer borrowers from their own countries. However, the top recipient is often in a region formerly colonized or geographically close to the each lender nation. These historical and geographical connections suggest a possible avenue for further analysis of lender motivation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subset the data set for top 10 lender countries\ntop_lenders <- lender_loans %>%\n  filter(country_code %in% c(\"US\", \"CA\", \"GB\", \"AU\", \"DE\", \"NL\", \"SE\", \"NO\", \"JP\", \"PH\"))\n\n# Find the top borrowers and their loan amounts for each of the lender country \ntop_lender_borrow <- aggregate(top_lenders$loan_amount, by = list(lender_country = top_lenders$country_code, borrower_country <- top_lenders$location.country), FUN = sum, na.rm = TRUE) %>%\n  mutate(lender_country = countrycode(lender_country, \"iso2c\", \"country.name\")) %>%\n  arrange(desc(x)) %>%\n  arrange(lender_country) %>%\n  group_by(lender_country) %>%\n  slice(1, 2, 3) %>% #Subset the top three borrowers for each lender country\n  mutate(x = format(x, big.mark = \",\", trim = TRUE)) %>%\n  rename(\"Loan Amount (USD)\" = \"x\", \"Lender Country\" = \"lender_country\", \"Borrower Country\" = \"Group.2\") %>%\n  group_by(`Lender Country`) %>%\n  mutate(`Borrower 1` = unique(`Borrower Country`)[1], \n         `Borrower 2` = unique(`Borrower Country`)[2], \n         `Borrower 3` = unique(`Borrower Country`)[3]) %>%\n  mutate(`Borrower 1` = ifelse(`Borrower 1` == \n         \"The Democratic Republic of the Congo\", \"DRC\", `Borrower 1`)) %>%\n  select(!c(`Borrower Country`, `Loan Amount (USD)`)) %>% #Reorganize table\n  distinct()\n\n# Format and output the table\nknitr::kable(top_lender_borrow, \"pipe\")\n```\n\n::: {.cell-output-display}\n|Lender Country |Borrower 1 |Borrower 2 |Borrower 3 |\n|:--------------|:----------|:----------|:----------|\n|Australia      |Cambodia   |Peru       |Uganda     |\n|Canada         |Peru       |Uganda     |Bolivia    |\n|Germany        |Peru       |Bolivia    |Cambodia   |\n|Japan          |Paraguay   |Cambodia   |Mongolia   |\n|Netherlands    |Uganda     |Peru       |Bolivia    |\n|Norway         |Uganda     |Bolivia    |Cambodia   |\n|Philippines    |DRC        |Uganda     |Rwanda     |\n|Sweden         |Uganda     |Bolivia    |Peru       |\n|United Kingdom |Uganda     |Peru       |Cambodia   |\n|United States  |Peru       |Uganda     |Bolivia    |\n:::\n:::\n\n\n#### Sector and gender of borrowers\n\nNext, we look at the composition of borrowers to get a better idea of which loans are funded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique borrower id and total male female borrower count\nloan_sub <- loans %>%\n  group_by(borrower_image_id) %>%\n  summarize(total_m = sum(borrower_m_count), total_f = sum(borrower_f_count))\n\n# Create new borrower type column based on conditions\nloan_sub <- loan_sub %>%\n  mutate(bor_type = if_else(total_m == 1 & total_f == 0, \"Male\",\n    if_else(total_m == 0 & total_f == 1, \"Female\", \"Group\")\n  ))\n\npc_gender <- subset(loan_sub, loan_sub$bor_type %in% c(\"Male\",\"Female\"))\n\nmerge <- left_join(x = lender_loans, y = pc_gender, by = \"borrower_image_id\")\n\n# Get the total loan amount for each gender\nsec_gender_loan <- merge %>%\n  group_by(sector, bor_type) %>%\n  summarise(tot_amount = sum(loan_amount) / 1000) %>%\n  arrange(desc(tot_amount))\n\n# Generate the gender proportion in borrowers\ntext <- aggregate(sec_gender_loan$tot_amount, by = list(gender = sec_gender_loan$bor_type), FUN=sum)\n\ncat(\"Female proportion:\", text$x[1]/(text$x[1]+text$x[2]), \"Male proportion:\", text$x[2]/(text$x[1]+text$x[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFemale proportion: 0.5854564 Male proportion: 0.4145436\n```\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n\nsec_gender_loan <- na.omit(sec_gender_loan)\n\n# Plot the sector by gender loan amounts\nggplot(sec_gender_loan) +\n  aes(x = reorder(sector, tot_amount), y = tot_amount, fill = bor_type, label = tot_amount) +\n  geom_bar(stat = \"identity\", position = \"dodge\") +\n  theme() +\n  guides(fill=guide_legend(title=\"Borrower Composition\"))+\n  coord_flip() +\n  xlab(\"Sector\") +\n  ylab(\"Total loan amount (thousand dollars)\") +\n  scale_fill_viridis(\n  discrete = TRUE,\n  option = \"D\")+\n  ggtitle(\"Sector vs Loan Amount by Gender\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/Sector loan amount with gender-1.png){width=672}\n:::\n:::\n\n\nOverall, the total loan amount of female borrowers (58.54%) exceeds that of male borrowers (41.45%). Similarly, female borrowers receive the majority of loan dollars. However, in Transportation, Construction, and Manufacturing, males receive a higher loan amount than female, while in Agriculture and Services, the loan amounts received by males and females are comparable. While we cannot conclude that these trends are due to lender preference, these differences suggest avenues for further exploration. For example, we might design our analysis to see if certain sectors are more likely to be funded than others, or if female applicants have a greater probability of having their loan funded. If so, this could suggest the priorities of lenders.\n\n### -- Part 2: Repayment Factors --\n\nNow we consider the second part of the prompt, which asks us to analyze the factors related to loan repayment.\n\nWe hypothesize that the borrower's sector could have a strong impact on the ability of borrowers to repay their loans. To explore this, we visualize the total value of loans by sector and payment status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Summarize the total loan amount and paid loan amount by sectors\nsector_loan <-\n  aggregate(lender_loans$loan_amount, by = list(sector = lender_loans$sector), FUN = sum)\nsector_paid <-\n  mutate(aggregate(lender_loans$paid_amount,\n    by = list(sector = lender_loans$sector),\n    FUN = sum, na.rm = TRUE\n  ))\n\n# Calculate the unpaid loan amount by sector in thousands USD\nby_sector <- sector_loan %>%\n  mutate(x = x/1000) %>% \n  mutate(paid = sector_paid$x/1000) %>%\n  mutate(unpaid = (x - paid)) %>%\n  rename(loan = x)\n\n# Generate status variable and rename the columns\nby_sector <- by_sector[order(by_sector$loan, decreasing = TRUE), ]\nby_sector_paid <- select(by_sector, sector, paid) %>%\n  mutate(status = \"paid\") %>%\n  rename(\"amount\" = \"paid\")\nby_sector_unpaid <- select(by_sector, sector, unpaid) %>%\n  mutate(status = \"unpaid\") %>%\n  rename(\"amount\" = \"unpaid\")\nby_sector <- rbind(by_sector_paid, by_sector_unpaid) %>%\n  group_by(sector)\n\n# Plot the Paid vs Unpaid loan amount by sector\nggplot(by_sector) +\n  aes(x = reorder(sector, amount), y = amount, fill = status, label = amount) +\n  geom_bar(stat = \"identity\", position = \"stack\") +\n  theme() +\n  coord_flip() +\n  xlab(\"Sector\") +\n  ylab(\"Loan amount (thousand dollars)\") +\n  scale_fill_viridis(\n  discrete = TRUE,\n  option = \"D\")+\n  ggtitle(\"Paid vs Unpaid Loan Amount by Sector\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/Sector, Paid amount-1.png){width=672}\n:::\n:::\n\n\nThe graph above shows that for most sectors, paid loans well exceed unpaid loans. Of the top five sectors in terms of loan amount, Agriculture has the highest proportion of unpaid loans, around 30%. Of all sectors, Housing and Education have the highest unpaid loans, nearly 50%. Arts has the lowest proportion of unpaid loans, about 18%. Hence, sector seems likely to be an important variable to include in subsequent analysis of loan repayment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Summarize default percent by gender and sector: exclude group loans\nloans_df <- loans %>% \n  filter(borrower_m_count < 2, borrower_f_count<2, \n         (status== \"Defaulted\" | status==\"Paid\")) %>%\n  mutate(borrower_female = ifelse(borrower_f_count ==1, \"Female\", \"Male\")) %>%\n  group_by(sector, borrower_female) %>%\n  dplyr::summarize(default_rate = sum(status == \"Defaulted\")/ n(), \n                   n_borrowers = n())\n\n#Compute the maximum default rate by sector\nloans_temp <- loans_df %>%\n  ungroup(borrower_female) %>%\n  dplyr::summarise(max_default_rate = max(default_rate), \n                   total_n_borrowers = sum(n_borrowers)) %>%\n  arrange(-total_n_borrowers)\n\n#Combine data frames and plot default rate by sector and gender\nleft_join(loans_temp, loans_df,  by = \"sector\") %>%\nggplot(aes(x = reorder(sector, max_default_rate), y = default_rate, fill = as.factor(borrower_female))) +\n  geom_bar(stat = \"identity\", position = position_dodge())  + \n  coord_flip() + \n  scale_fill_viridis(discrete = TRUE) + \n  labs(title = \"Default rate by sector and gender\", y = \"Loan default rate\", \n       x = \"\", fill = \"Borrower sex\")\n```\n\n::: {.cell-output-display}\n![](EDA-Jenny-Final_files/figure-html/Default rate by sector and gender-1.png){width=672}\n:::\n:::\n\n\nFrom the graph above, we can see that in Personal Use, Manufaturing, Housing, and Transportation sectors, males have a higher default rate than females, while in Health, the trend appears to be the opposite. It's worth noting that in Entertainment and Education, female loan defaults are incredibly rare, while in the Wholesale sector only female borrowers defaulted their loans, and male defaults are very rare. In other sectors, the default rates for both males and females are similar. This suggests we might want to consider sector, or potentially sector-sex interactions in our loan repayment analysis.\n\n### Conclusion\n\nIn this section, we observe several interesting trends in regards to lender motivation and loan repayment. In terms of lender motivation, we notice that certain sectors and female borrowers seem disproportionately represented, indicating further directions for analysis. However, we also find that lending patterns vary by lending country, suggesting heterogeneity of lender motivation. In terms of loan repayment, we notice variability in loan default frequency in terms of `sector`. This could reflect a potential predictor of the borrower's ability to repay. However, it is important to note that borrower country could be a confounding variable: if a large borrower nation is dominated by one sector, it may be difficult to disentangle the effect of the sector from the effects of that country's general economic climate. Hence, as we further explore loan repayment factors, it may be necessary to control for regional and country-level effects.\n",
    "supporting": [
      "EDA-Jenny-Final_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}